// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNPA_CTE97-ZJnb9VvhNwNAn4LR7v4bqM',
    appId: '1:1045119223855:web:ab9e812c17544a268a1eda',
    messagingSenderId: '1045119223855',
    projectId: 'takafultest-2ef6f',
    authDomain: 'takafultest-2ef6f.firebaseapp.com',
    storageBucket: 'takafultest-2ef6f.appspot.com',
    measurementId: 'G-VJN2NBMXPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABD7dWivy1Z7QZ76GbSdPVpCK6TJLvBCY',
    appId: '1:1045119223855:android:96e1cf2c8b299b288a1eda',
    messagingSenderId: '1045119223855',
    projectId: 'takafultest-2ef6f',
    storageBucket: 'takafultest-2ef6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8dJhe013nNCPutWpMmmZqe7r70fx8Ogo',
    appId: '1:1045119223855:ios:52ccfc845e95df3d8a1eda',
    messagingSenderId: '1045119223855',
    projectId: 'takafultest-2ef6f',
    storageBucket: 'takafultest-2ef6f.appspot.com',
    iosClientId:
        '1045119223855-p7f8hr6hl0qquut2hfb7d834687pp7od.apps.googleusercontent.com',
    iosBundleId: 'com.example.takaful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8dJhe013nNCPutWpMmmZqe7r70fx8Ogo',
    appId: '1:1045119223855:ios:52ccfc845e95df3d8a1eda',
    messagingSenderId: '1045119223855',
    projectId: 'takafultest-2ef6f',
    storageBucket: 'takafultest-2ef6f.appspot.com',
    iosClientId:
        '1045119223855-p7f8hr6hl0qquut2hfb7d834687pp7od.apps.googleusercontent.com',
    iosBundleId: 'com.example.takaful',
  );
}
